// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqCuJtCDZ3EYQTXv816cTq4sK6K37H9KE',
    appId: '1:303451786596:web:cbe3735f855c831c3b3e71',
    messagingSenderId: '303451786596',
    projectId: 'vachak-5ce71',
    authDomain: 'vachak-5ce71.firebaseapp.com',
    storageBucket: 'vachak-5ce71.appspot.com',
    measurementId: 'G-Z68NH1Z3HE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYjhMCdcAKTjLsxYRhza-4yB-dWvQRkps',
    appId: '1:303451786596:android:ae1c1fdfed0e6e2a3b3e71',
    messagingSenderId: '303451786596',
    projectId: 'vachak-5ce71',
    storageBucket: 'vachak-5ce71.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6XAbAIoQneL07yR6jnUDJEUDWgBFlkCs',
    appId: '1:303451786596:ios:39158ce2ace716d43b3e71',
    messagingSenderId: '303451786596',
    projectId: 'vachak-5ce71',
    storageBucket: 'vachak-5ce71.appspot.com',
    iosBundleId: 'com.armid.vachak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6XAbAIoQneL07yR6jnUDJEUDWgBFlkCs',
    appId: '1:303451786596:ios:39158ce2ace716d43b3e71',
    messagingSenderId: '303451786596',
    projectId: 'vachak-5ce71',
    storageBucket: 'vachak-5ce71.appspot.com',
    iosBundleId: 'com.armid.vachak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqCuJtCDZ3EYQTXv816cTq4sK6K37H9KE',
    appId: '1:303451786596:web:2f3e88468fc977fd3b3e71',
    messagingSenderId: '303451786596',
    projectId: 'vachak-5ce71',
    authDomain: 'vachak-5ce71.firebaseapp.com',
    storageBucket: 'vachak-5ce71.appspot.com',
    measurementId: 'G-VSYD5RGZ71',
  );
}
